The container started executing and for some reason failed, terminated reason! = "Completed"